# Generated by Django 3.1.2 on 2020-10-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategory',
            name='sort',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
