# Generated by Django 3.1.2 on 2020-10-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_skillcategory_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resume.skillcategory'),
        ),
    ]
