# Generated by Django 3.1.2 on 2020-10-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_skillcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
