# Generated by Django 3.1.2 on 2020-10-27 13:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_mainprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainprofile',
            name='catchphrase_el',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainprofile',
            name='catchphrase_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainprofile',
            name='name_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainprofile',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainprofile',
            name='story_el',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainprofile',
            name='story_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainprofile',
            name='surname_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainprofile',
            name='surname_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
