# Generated by Django 3.1.2 on 2020-10-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='sort',
            field=models.IntegerField(default=1),
        ),
    ]
