# Generated by Django 3.1.2 on 2020-10-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20201027_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofile',
            name='cv',
            field=models.FileField(upload_to='porfolio/uploads/'),
        ),
    ]
