# Generated by Django 3.1.2 on 2020-10-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20201027_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
