# Generated by Django 3.1.3 on 2020-11-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_mainprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description_el',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='duties_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='duties_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responsibilities',
            name='title_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responsibilities',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
