# Generated by Django 3.1.2 on 2020-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20201022_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
