# Generated by Django 3.1.2 on 2020-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20201023_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='technologies',
            field=models.ManyToManyField(to='portfolio.Technology'),
        ),
    ]
