# Generated by Django 3.1.2 on 2020-10-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20201023_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
