# Generated by Django 3.1.2 on 2020-10-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_portfolio_social_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
