# Generated by Django 3.1.2 on 2020-10-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20201026_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
