# Generated by Django 3.1.2 on 2020-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201026_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
