# Generated by Django 3.1.3 on 2020-11-02 11:17

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201102_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comp_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='feat_image',
            field=image_optimizer.fields.OptimizedImageField(upload_to='blog/images'),
        ),
    ]
